version: 0.2   
env:
  PORT: "3000"
  XBEE_STAGE: "test"
  NODE_ENV: "development"
  CI: "true"

     
phases:
  install:
    commands:
      - ls -lha
      - echo current node version `node --version`
      - echo Installing system packages
      - echo Installing global dependencies
      - npm install -g yarn
      - yarn global add lerna            

  pre_build:
    commands:
      - echo Bootstrap source code
      - yarn
      - lerna bootstrap      
  
  build:
    commands:  
      - npm run web:build
      - npm web:test

artifacts:
  files:
    - "packages/xcoobee-cookie-kit-web/dist/**/*"    
  name: cookie-kit-$(date +%Y-%m-%d) 